// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdCRLY5-CM73vMKz6w7WBhdme5g1oMas',
    appId: '1:84196108863:web:4b1ae2b619b20ef346668a',
    messagingSenderId: '84196108863',
    projectId: 'todo-ef4df',
    authDomain: 'todo-ef4df.firebaseapp.com',
    storageBucket: 'todo-ef4df.appspot.com',
    measurementId: 'G-9BSJEXB5WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjJ1iPX1hAILwTAhHnnDa9yr6Ecll5Do',
    appId: '1:84196108863:android:d4f500583196b74346668a',
    messagingSenderId: '84196108863',
    projectId: 'todo-ef4df',
    storageBucket: 'todo-ef4df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0YnBANTFBqjc5V6o33Z0XXW16dDY2ao',
    appId: '1:84196108863:ios:ec823583508c411746668a',
    messagingSenderId: '84196108863',
    projectId: 'todo-ef4df',
    storageBucket: 'todo-ef4df.appspot.com',
    iosBundleId: 'com.example.todoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0YnBANTFBqjc5V6o33Z0XXW16dDY2ao',
    appId: '1:84196108863:ios:f23771c6f4013f0846668a',
    messagingSenderId: '84196108863',
    projectId: 'todo-ef4df',
    storageBucket: 'todo-ef4df.appspot.com',
    iosBundleId: 'com.example.todoApplication.RunnerTests',
  );
}
